<?php

// This file is automatically generated. Do not edit manually.

return array (
  'alhelalat' => 
  array (
    'password' => '$2y$10$eS5zoIV./q6NhoNbIING5.Hcac8Bb6wTbmR.KTnI6g0Yz8DUWuUaG',
    'permissions' => 
    array (
      0 => '*',
    ),
  ),
);
