<?php
/**
 * Data Helper Functions
 *
 * Provides centralized functions for accessing and modifying
 * application data like users and workspaces.
 */

function getWorkspaces() {
    $file = DATA_PATH . '/workspaces.php';
    if (!file_exists($file)) {
        // Fallback check for old workspaces.json during migration
        $oldFile = DATA_PATH . '/workspaces.json';
        if (file_exists($oldFile)) {
            $data = json_decode(file_get_contents($oldFile), true);
            if (is_array($data)) {
                saveWorkspaces($data);
                @unlink($oldFile);
                return $data;
            }
        }
        return [];
    }
    return readSecurePhpJson($file) ?? [];
}

function getUsers() {
    $file = DATA_PATH . '/users/users.php';
    if (!file_exists($file)) {
        return [];
    }
    // Use include to read the PHP array. This is safer than eval().
    $users = include($file);
    if (!is_array($users)) {
        throw new Exception("Users file at '{$file}' is corrupted or does not return an array.");
    }
    return $users;
}

function saveWorkspaces($workspaces) {
    $file = DATA_PATH . '/workspaces.php';
    if (writeSecurePhpJson($file, $workspaces) === false) {
        throw new Exception("Unable to save workspaces.php file. Please check permissions on the /data directory.");
    }
}

function saveUsers($users)
{
    $file = DATA_PATH . '/users/users.php';
    // Use var_export to generate a PHP-readable array representation, wrapped in PHP tags.
    $content = "<?php\n\n// This file is automatically generated. Do not edit manually.\n\nreturn " . var_export($users, true) . ";\n";
    if (file_put_contents($file, $content, LOCK_EX) === false) {
        throw new Exception("Unable to save users file. Check permissions for the 'data/users' directory.");
    }
    if (function_exists('opcache_invalidate')) {
        opcache_invalidate($file, true);
    }
}
